public: "true"
type: "docs"
category: "arrangement and description"
tags:
  - "policy"

title: "Culturally Competent (Re)Description Education Campaign"
description: "Summary of the RAC's CCD education campaign"
pages:
  - ["Culturally Competent (Re)Description Education Campaign", "index"]
